# 工程根目录运行: 
# docker-compose -f ./docker/docker-compose-etcd.yml up
# docker-compose -f ./docker/docker-compose-etcd.yml down

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.12
    container_name: etcd
    volumes:
      - snpp-etcd-data:/etcd-data
    environment:
      - TZ=UTC
      - ETCD_NAME=etcd
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://172.17.177.138:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ALLOW_NONE_AUTHENTICATION=yes #- ETCD_ROOT_PASSWORD=1 #pwd for root 
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - snpp-network
    restart: unless-stopped

  etcdkeeper:
    image: evildecay/etcdkeeper:v0.7.6
    container_name: etcdkeeper
    ports:
      - "8081:8080"
    environment:
      - ETCD_HOST=http://172.17.177.138
      - ETCD_PORT=2379
      #- ETCD_USERNAME=  # 如果有认证
      #- ETCD_PASSWORD=  # 如果有认证
    depends_on:
      - etcd
    networks:
      - snpp-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
volumes:
  snpp-etcd-data:
    driver: local

networks:
  snpp-network:
    driver: bridge

